### ISSUE TITLE
Add support for photos in MyWatchList

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#27]
We should be using the Google Images API to get the url of images for shows that get entered into the database, so that we can show cover art to users, most likely by setting the embed's thumbnail.

**Comment by tjmorin327** [comment]
Added support for thumbnail in embed
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/134175801/2f372005-9f73-45d4-bcdd-7fb60d865682)
