### ISSUE TITLE
MyWatchList embeds with over 25 fields are unable to show more data

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#28]
We will need an alternate approach for !history to display more than 7 shows of data, one approach would be to concatenate into a string and include markdown and rather that using ```embed.add_field``` we can add to the em bed's description, a similar approach was done in !queue.
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/55159220/907c3774-3c23-495a-90a0-d4e25a7de57f)

**Comment by aaronrai24** [comment]
Linking [MarkdownCheatSheet](https://www.markdownguide.org/cheat-sheet/)

**Comment by tjmorin327** [comment]
Allowed for more than 7 historical entries with multiple embeds. Need to consider markdown as alternative potentially.
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/134175801/a7ac71d6-6b29-4eeb-bd71-33c4d3d07eca)
