### ISSUE TITLE
Removing from active watchlist should notify user

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#29]
Feature request: We should include a message to the user to notify that this show no longer exists in their active watchlist. For example: 'Looks like you finished X, adding to your history!

Submitted by: Cash#8915
Server: SHMEAT

**Comment by tjmorin327** [comment]
Added message to address when !addhistory also removes from WatchList
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/134175801/2c357eb7-ead2-4647-9843-2daeb6af8eca)
