### ISSUE TITLE
Add MyWatchList

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#3]
Feature request: Feature for users to submit what shows/tv/anime they have seen and what grade they would rate that genre of entertainment, would require some sort of persistent storage(db)

Submitted by: Cash#8915
Server: mfTesting

**Comment by aaronrai24** [comment]
Either we can use [MySQL](https://dev.mysql.com/doc/mysql-yum-repo-quick-guide/en/) which would be simpler, or [SQlite](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-sqlite-on-ubuntu-20-04) which would be more lightweight considering this will be installed on Dollar's server and disk space is fairly limited.

**Comment by tjmorin327** [comment]
223947980309397506
-update patchnotes
-create md for watchlist commands

- extract emoji translation to outside function ln 505

*WatchList Table*
!addshow
- sanitize inputs

!wl
- format output into discord embed
- image query for first item

!editorder
- print current wl
- prompt for show to edit
- prompt for new index
- grab list to update
- iteratively update each entry

!removeshow
- call remove function


*WatchHistoryTable*
- create WatchHistory table
- add commands
- commands: add to list, edit entry/rating, remove entry

!addhistory
- adds entry to 'completedtable' and removes from wl if exist

!edithistory
- changes rating on existing entry
- prompt for show name
- prints current rating and prompts for new rating
- ack new rating

!removehistory
- remove from wl (update indexes accordingly)
- prompt for show name
- verify show name exists
- remove from list


*remove from wl*
select * from table where user = userID
and TableIndex > index
editList = results ^^
update iteratively to TableIndex--

**Comment by tjmorin327** [comment]
Submitted changes to main
