### ISSUE TITLE
!clearhistory for myWatchlist

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#30]
Feature request: We should have a command that will clear all entires in the watch history table, this will 100 percent need a validation to make users aware they are clearing their whole watch history

Submitted by: Cash#8915
Server: SHMEAT

**Comment by tjmorin327** [comment]
Added !clearhistory command 
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/134175801/f183e05b-2fbf-4052-a766-42553ca6ee38)
