### ISSUE TITLE
!addshow and !addhistory dont check for duplicate ShowName

### ISSUE THREAD

**Issue by aaronrai24** [aaronrai24/DollarDiscordBot#39]
Bug report: !addshow allows it and !addhistory throws error

Submitted by: Tom 💧#2224
Server: SHMEAT

**Comment by tjmorin327** [comment]
Added checks to see if entry already exists. 
![image](https://github.com/aaronrai24/DollarDiscordBot/assets/134175801/66f2b850-1b72-4b15-84fa-d9ecf6e636b0)
